server:
  port: 8765

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: user-service-custom
          uri: lb://user-service
          predicates:
            - Path=/api/auth/**

        - id: flight-service
          uri: lb://FLIGHT-SERVICE
          predicates:
            - Path=/flight-service/**
          filters:
            - AuthenticationFilter
            - name: CircuitBreaker
              args:
                name: flightCircuitBreaker
                fallbackUri: forward:/fallback/flight

        - id: booking-service
          uri: lb://BOOKING-SERVICE
          predicates:
            - Path=/booking-service/**
          filters:
            - AuthenticationFilter
            - name: CircuitBreaker
              args:
                name: bookingCircuitBreaker
                fallbackUri: forward:/fallback/booking

eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

resilience4j:
  circuitbreaker:
    instances:
      flightCircuitBreaker:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10000
        permittedNumberOfCallsInHalfOpenState: 3
      bookingCircuitBreaker:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10000
        permittedNumberOfCallsInHalfOpenState: 3
  timelimiter:
    instances:
      flightCircuitBreaker:
        timeoutDuration: 2s
      bookingCircuitBreaker:
        timeoutDuration: 2s