server:
  port: 8765

spring:
  application:
    name: API-GATEWAY
	cloud:
	    gateway:
	      discovery:
	        locator:
	          enabled: true
	          lower-case-service-id: true
	      
	      # --- NEW: Explicit Routes to apply Security & Circuit Breakers ---
	      routes:
	        # 1. USER SERVICE (OPEN - No Security Filter)
	        # This allows Login/Signup to pass through
	        - id: user-service
	          uri: lb://USER-SERVICE
	          predicates:
	            - Path=/api/auth/**

	        # 2. FLIGHT SERVICE (SECURED + Circuit Breaker)
	        - id: flight-service
	          uri: lb://FLIGHT-SERVICE
	          predicates:
	            - Path=/flight-service/**
	          filters:
	            - AuthenticationFilter # <--- Your JWT Security
	            - name: CircuitBreaker
	              args:
	                name: flightCircuitBreaker
	                fallbackUri: forward:/fallback/flight # Optional: if you have a fallback

	        # 3. BOOKING SERVICE (SECURED + Circuit Breaker)
	        - id: booking-service
	          uri: lb://BOOKING-SERVICE
	          predicates:
	            - Path=/booking-service/**
	          filters:
	            - AuthenticationFilter # <--- Your JWT Security
	            - name: CircuitBreaker
	              args:
	                name: bookingCircuitBreaker
	                fallbackUri: forward:/fallback/booking

eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

resilience4j:
  circuitbreaker:
    instances:
      flightCircuitBreaker:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10000
        permittedNumberOfCallsInHalfOpenState: 3
      bookingCircuitBreaker:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10000
        permittedNumberOfCallsInHalfOpenState: 3
  timelimiter:
    instances:
      flightCircuitBreaker:
        timeoutDuration: 2s
      bookingCircuitBreaker:
        timeoutDuration: 2s